// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  bgnews: require('../Images/Launcher/Splash.png'),
  logo_blue: require('../Images/logo_blue.png'),
  email: require('../Images/Sosial/Email.png'),
  facebook: require('../Images/Sosial/Facebook.png'),
  twitter: require('../Images/Sosial/Twitter.png'),
  whatsapp: require('../Images/Sosial/Whatsapp.png'),
  eye: require('../Images/CustomIcon/Eye.png'),
  share: require('../Images/CustomIcon/Share.png'),
  search: require('../Images/CustomIcon/Search.png'),
  menu: require('../Images/CustomIcon/HamburgerMenu.png'),
  arrowRight: require('../Images/CustomIcon/ArrowRight.png'),
  arrowLeft: require('../Images/CustomIcon/ArrowLeft.png'),
  cancel: require('../Images/CustomIcon/Cancel.png'),
  newsMenu: require('../Images/IconMenu/News.png'),
  videosMenu: require('../Images/IconMenu/Video.png'),
  shopMenu: require('../Images/IconMenu/Shop.png'),
  rewardMenu: require('../Images/IconMenu/Reward.png'),
  subscripMenu: require('../Images/IconMenu/Subscription.png'),
  accMenu: require('../Images/IconMenu/Account.png'),
  advMenu: require('../Images/IconMenu/Advertise.png'),
  setMenu: require('../Images/IconMenu/Setting.png'),
  logoutMenu: require('../Images/IconMenu/Logout.png')

}

export default images
